name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Install XGBoost
    - name: Install XGBoost
      run: sudo apt-get install -y libxgboost-dev

    # Install other dependencies if needed
    - name: Install build essentials
      run: sudo apt-get install -y build-essential

    # Build the project using Makefile
    - name: Build with Makefile
      run: make

    # Run the program
    - name: Run the program
      run: ./main
